version: "3.3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=hr_dbs
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - LANG=ru_RU.UTF-8
      - LANGUAGE=ru_RU:ru
      - LC_ALL=ru_RU.UTF-8

    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: