# Generated by Django 4.0 on 2021-12-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='possible_answer',
            field=models.SmallIntegerField(choices=[(1, 'Верен'), (2, 'Неверен')], default=1, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.SmallIntegerField(choices=[(2, 'Несколько правильных ответов'), (1, 'Один правильный ответ'), (3, 'Ввести свой ответ')], verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='текст ответа пользователя'),
        ),
    ]
