# Generated by Django 4.0 on 2021-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answer_possible_answer_alter_question_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='possible_answer',
            field=models.SmallIntegerField(choices=[(2, 'Неверен'), (1, 'Верен')], default=1, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.SmallIntegerField(choices=[(1, 'Один правильный ответ'), (3, 'Ввести свой ответ'), (2, 'Несколько правильных ответов')], verbose_name='Тип вопроса'),
        ),
    ]
