# Generated by Django 4.0 on 2022-01-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_id_useranswer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='s_types',
            field=models.SmallIntegerField(choices=[(2, 'Опрос'), (1, 'Тест')], null=True, verbose_name='Тип опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.SmallIntegerField(choices=[(3, 'Ввести свой ответ'), (2, 'Несколько правильных ответов'), (1, 'Один правильный ответ')], verbose_name='Тип вопроса'),
        ),
    ]
