# Generated by Django 4.0 on 2022-01-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_types_alter_survey_s_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.SmallIntegerField(choices=[(2, 'Несколько правильных ответов'), (3, 'Ввести свой ответ'), (1, 'Один правильный ответ')], verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='main.answer'),
        ),
    ]
