# Generated by Django 4.0 on 2022-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_question_types_alter_useranswer_answer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['s_types'], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='types',
            field=models.SmallIntegerField(choices=[(3, 'Ввести свой ответ'), (2, 'Несколько правильных ответов'), (1, 'Один правильный ответ')], verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='s_types',
            field=models.SmallIntegerField(choices=[(2, 'Опрос'), (1, 'Тест')], null=True, verbose_name='Тип опроса'),
        ),
    ]
